config/routes.rb
Blog::Application.routes.draw do
  get 'tags/:tag', to: 'articles#index', as: :tag
  
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :articles
    root to: 'articles#index'
  end

  match '', to: redirect("/#{I18n.default_locale}")

end

app/models/article.rb
class Article < ActiveRecord::Base
  translates :nome, :content, :tag_list
  attr_accessible :content, :nome, :tag_list
  has_many :taggings
  has_many :tags, through: :taggings

def self.tagged_with(name)
  Tag.find_by_name!(name).articles
end

def self.tag_counts
  Tag.select("tags.*, count(taggings.tag_id) as count").
    joins(:taggings).group("taggings.tag_id")
end

def tag_list
  tags.map(&:name).join(", ")
end

def tag_list=(names)
  self.tags = names.split(",").map do |n|
    Tag.where(name: n.strip).first_or_create!
  end
end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale

private

  def set_locale
  	I18n.locale = params[:locale] if params[:locale].present?
  end

  def default_url_options(options = {})
  {locale: I18n.locale}
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    if params[:tag]
    @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.all
    end
  end
  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def tag_cloud(tags, classes)
  max = tags.sort_by(&:count).last
  tags.each do |tag|
    index = tag.count.to_f / max.count * (classes.size - 1)
    yield(tag, classes[index.round])
   end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= semantic_form_for @article do |f|
  = f.inputs
  = f.input :tag_list, label: "Tags (separated by commas)"
  = f.button

app/views/articles/edit.html.haml
%h1 Editing article
= render 'form'
= link_to 'Show', @article
= link_to 'Delete', @article, method: :delete, data: { confirm: 'Voce tem certesa?' }
|
\#{link_to 'Back', articles_path}

app/views/articles/index.html.haml
%h1= t ".title"
%table
  #tag_cloud
    - tag_cloud Article.tag_counts, %w[s m l] do |tag, css_class|
      = link_to tag.name, tag_path(tag.name), class: css_class
  - @articles.each do |article|
    %tr
      %td
        %h1
          = link_to article.nome, article
    %tr
      %td= article.content
    %tr
    %td
      = raw article.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join (', ')
    %tr
    %td= link_to 'Edit', edit_article_path(article)
%br/
= link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New article
= render 'form'
= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice
%p
  %b Nome:
  = @article.nome
%p
  %b Content:
  = @article.content
= link_to 'Edit', edit_article_path(@article)
|
\#{link_to 'Back', articles_path}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	Language:
	<%= link_to_unless_current "English", locale: "en" %> |
	<%= link_to_unless_current "Portuguese", locale: "pt" %>
<%= yield %>

</body>
</html>